version: '3'
services:
  web:
    build: 
      context: . #current dir
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app #current folder into /app
  
  # no need for port, override command
  tests:
    build: 
      context: . #current dir
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app #current folder into /app
    command: ["npm", "run", "test"]    